### ISSUE TITLE
Error when following the contributing  process

### ISSUE THREAD

**Issue by chriswedgwood** [django-crispy-forms/crispy-tailwind#104]
Looking to add a documentation PR I did the following:

forked and cloned
python -m venv venv
source ./venv/bin/activate
(venv) pip install -r requirements.txt

![image](https://user-images.githubusercontent.com/1273523/128360285-bba2f9ee-39a8-45f8-b77e-8dea026e1027.png)

Looking at the requirements file there isn't any pinning. 

Will get a working version and then pin?

**Comment by smithdc1** [comment]
That would be great thank you. 🙏

Not immediately obvious to why that's happening but looking more closely can wait. It seems sometimes just pinning things and leaving them a while can be the best approach. 🤷‍♂️
