### ISSUE TITLE
Release for django 4.0

### ISSUE THREAD

**Issue by dreaquil** [django-crispy-forms/crispy-tailwind#122]
Hi!

I see that there were some bug fixes for django 4.0 on the main branch. Is there a plan to create a release for this? Thanks!

**Comment by smithdc1** [comment]
Yes there is!

I'm currently working on crispy-forms 2.0. Once I've got that out, I'll circle round the other template packs and make sure they all work with that release, latest versions of python/django. 

https://github.com/django-crispy-forms/django-crispy-forms/pull/1294

If there's fixes we need to make now then PRs are very much welcomed. 🙏

**Comment by fedosov** [comment]
Hi @smithdc1

I am writing to kindly request the possibility of a new release of crispy-tailwind. 🙏

**Comment by GitRon** [comment]
It works for me with Django 5.0. @dreaquil, is this issue still an issue?

**Comment by GitRon** [comment]
Apparently not. I'll close this one.
