### ISSUE TITLE
select_option.html inherits parent attributes

### ISSUE THREAD

**Issue by nikolaysm** [django-crispy-forms/crispy-tailwind#132]
There is an option to enable and disable  parent attributes for options at `ChoiceWidget`:

<img width="794" alt="image" src="https://user-images.githubusercontent.com/3074155/220918396-98330672-e856-4351-b137-b510976632e8.png">

https://github.com/django/django/blob/5b3d3e400ab9334ba429ca360c9818c6dfc3a51b/django/forms/widgets.py#L585

So `select_option.html` doesn't take this into account.

One of the solutions is to use `field.field.widget.option_inherits_attrs`:

`<option value="{{ value|stringformat:'s' }}"`**` {% if field.field.widget.option_inherits_attrs %} {{ field.field.widget.attrs|flatatt }}{% endif %}`**`{% if field.value|stringformat:'s' == value|stringformat:'s' %} selected{% endif %}>{{ label }}</option>`

**Comment by hongquan** [comment]
PR to fix has been made: https://github.com/django-crispy-forms/crispy-tailwind/pull/133
