### ISSUE TITLE
Invite Ronny Vedrilla to team. 

### ISSUE THREAD

**Issue by carltongibson** [django-crispy-forms/crispy-tailwind#147]
I'd like to propose adding Ronny @GitRon to the team for crispy-tailwind. 

I can vouch for Ronny personally. He's a lovely person. And crispy-tailwind could do with more bandwidth.

@smithdc1 I don't believe you're actively using tailwind right? Whilst I am, I'm not currently using crispy for that (as part of my experiment into _What Now?_ given the Django 4.x+ forms changes). Ronny is going both, and is well placed to take the lead here. 

Whilst we're here, I'd state my thoughts on the scope/goals: 

* Keep it small — it's a demonstration of what you can do, and a starting point, not an always solution. 
* Link to and document other things in _How-Tos_
* Encourage folks to override what they want to in their own projects.

**Comment by smithdc1** [comment]
Hi @carltongibson & @GitRon, Happy New Year to you both. 

This is great. 🎉  The project could certainly do with more bandwidth, also my knowledge of Tailwind is pretty basic. 

Carlton -- Are you able to help with the invite? I had a look and got a bit lost on what I should do. It seems more complicated than last time I looked!

**Comment by carltongibson** [comment]
OK, done, I think 😅

I invited Ronny to the crispy forms core team, added access to all the crispy repos there, and set the Triage role (which should allow close/merging/... PRs and such.) 

@GitRon Welcome aboard! Go! 🎉  Shout if you want input, or if the permissions aren't right or... — Both @smithdc1 and I watch the repos say if you need anything. 🎁

**Comment by GitRon** [comment]
Thanks, guys! It's the first time for me maintaining a package together with other people!

Hence I have some questions:
* Am I supposed to merge PRs as well?
* Who's doing a release and when? Merged branches are nice but if it's not released, it basically didn't happen.

**Comment by GitRon** [comment]
Good point! Forgot about the change notes in the last ticket. Will add it for my current PR.

**Comment by GitRon** [comment]
OK, once https://github.com/django-crispy-forms/crispy-tailwind/pull/146 is merged, I'd suggest a release. The last one was ages ago and @smithdc1 did already some changes to the metadata in October which never saw the light of day 😅 

Are you ok with this?

**Comment by carltongibson** [comment]
Yep, sounds good. 

If you get it ready, or as close as you can, then that's amazing. It really helps.

**Comment by GitRon** [comment]
The PR is merged. Nothing open from my side 🙂

**Comment by smithdc1** [comment]
How about switching to CalVer? 🤔

**Comment by carltongibson** [comment]
Yeah! +1 for CalVer.

**Comment by GitRon** [comment]
Hm, I think it's great for certain packages like my [meta-package-updater](https://github.com/ambient-innovation/ambient-package-update) because it doesn't contain any code.

I like semVer a lot because when I update the package I know what to except. Bugfix release? No need to worry. Major release? Let's have a deep dive into the changelog. CalVer Doesn't provide that.

My 5c on the topic 🙂

**Comment by justinmayer** [comment]
I was going to suggest automating releases via [AutoPub](https://justinmayer.com/projects/autopub/), but I don't believe it supports CalVer (yet). 😊

**Comment by carltongibson** [comment]
My jaded take on breaking changes is that they're all breaking changes. 😅 Folks complain no matter what. SemVer writes checks poor maintainers can't cash: let 'em read the release notes. 

(This may apply all the more for template heavy packages, where folks write CSS/JS to match the HTML exactly...)  

Happy to go with the consensus though.

**Comment by justinmayer** [comment]
Folks will indeed complain no matter what, but I'm not sure that's a good justification for CalVer. I prefer SemVer because it at least conveys _some_ information regarding what lies within, whereas CalVer feels to me like an unnecessary capitulation.

SemVer is a _guide_ for users and not a promise, and therefore to me it's not akin to writing checks doomed to bounce. As for folks who have an expectation that SemVer is a promise, I say let those misguided folks complain as much as they like.

Just my take on this topic, of course. 😊

**Comment by GitRon** [comment]
In general, I agree with @justinmayer but Carlton has a point:

> (This may apply all the more for template heavy packages, where folks write CSS/JS to match the HTML exactly...)

**Comment by carltongibson** [comment]
@justinmayer Can we get you to DjangoCon and we can wrestle for it 😜 

🎁

**Comment by GitRon** [comment]
I've already bought tickets 🙃

**Comment by GitRon** [comment]
The discussion about having a release ASAP got a little bit derailed 😅 

If @justinmayer could to the changes for the auto-versioning reasonably soon, I'd take this as a killer argument pro semVer. If he can't do that (which is of course perfectly fine!), I'd put up a vote between calVer and semVer and do a 0.6.0 release so we get all the new stuff shipped out-

Can we agree on that roadmap? 🙂

**Comment by carltongibson** [comment]
Don't let the version number delay you! (Not that much hangs on it 😅)

**Comment by GitRon** [comment]
I think I can't do the release, right? The question is: Who can? 😅

**Comment by carltongibson** [comment]
@smithdc1 can. But you can get it close 😉. 

(The actual `twine upload` bit is the least of it...)

**Comment by smithdc1** [comment]
https://github.com/django-crispy-forms/crispy-tailwind/blob/main/.github%2Fworkflows%2Fpublish.yml

We've a workflow setup. It's "just" a matter of creating a GH Release. I'm happy to do that, just need to make sure version number is updated etc.

**Comment by justinmayer** [comment]
> If @justinmayer could to the changes for the auto-versioning reasonably soon, I'd take this as a killer argument pro semVer. If he can't do that (which is of course perfectly fine!), I'd put up a vote between calVer and semVer and do a 0.6.0 release so we get all the new stuff shipped out

I would be more than happy to set that up. The configuration I would recommend would include publishing via PyPI's new Trusted Publisher system, and it also would automatically create the GitHub Release as part of the release process.

**Comment by GitRon** [comment]
@smithdc1 What do I have to do? Just update the version number somewhere in the code?

@justinmayer I'd be happy about a PR, sounds like a neat solution. I guess the others agree?

**Comment by smithdc1** [comment]
@GitRon https://github.com/django-crispy-forms/crispy-tailwind/blob/main/crispy_tailwind%2F__init__.py

Just here I think. 

Thanks for all your efforts here!

**Comment by GitRon** [comment]
Hi @smithdc1 - I've created a PR with the version dump and updated the changelog: https://github.com/django-crispy-forms/crispy-tailwind/pull/148

Do you need anything else?

**Comment by GitRon** [comment]
@smithdc1 Code has been merged, you can do the release now I guess 😊

**Comment by smithdc1** [comment]
Thank you @GitRon ! ❤️ 

https://pypi.org/project/crispy-tailwind/1.0.0/ 🎉
