### ISSUE TITLE
PyPI release

### ISSUE THREAD

**Issue by stevejalim** [django-crispy-forms/crispy-tailwind#17]
Heya there

I know this project is pretty young, but is there a chance of a pypi release, in line with the readme?

```
$ pip3 install crispy_tailwind

ERROR: Could not find a version that satisfies the requirement crispy_tailwind (from versions: none)
ERROR: No matching distribution found for crispy_tailwind
``` 

I know it's possible to `-e` the git URL in requirements.txt, but in a Docker build that results in the dependency being installed at the user, not system level, making it effectively invisible to the app.

Cheers!

**Comment by carltongibson** [comment]
> I know it's possible to -e the git URL in requirements.txt, but in a Docker build that results in the dependency being installed at the user, not system level, making it effectively invisible to the app.

Can you explain this a bit please? My initial response is, surely you're just holding it wrong...? But no doubt you're hitting a real issue. 

Thanks.

**Comment by stevejalim** [comment]
Heya Carlton

Ha, yeah. It's entirely possible I am not Doing it Right. The Docker image is a v slim Alpine one, so needs git adding explicitly. It's possible this is the root cause - I'll look into other ways to install git that might let pip install system-wide like with regular deps.  Will circle back later

Cheers for the prompt reply

Steve

**Comment by carltongibson** [comment]
I’ve heard folk who know about this recommending buster-slim, rather than Alpine, because it’s no much bigger in the end and you get much quicker builds...

**Comment by stevejalim** [comment]
Yeah, I was about to try swapping to that to save myself the grief. Will
let you know how it goes!

**Comment by carltongibson** [comment]
Hi @stevejalim. Also, You say “system”... — if you’re not, I’d be inclined to still use a virtual env, even though it’s in Docker. That way you know exactly which interpreter is is play, and how pip will work and ... (Plus the setup is the same as when you’re not containerised.) 

Anyhow, please do report back.
