### ISSUE TITLE
Form alerts look odd

### ISSUE THREAD

**Issue by AliMejbar** [django-crispy-forms/crispy-tailwind#74]
Hello ,
Thank's for this repo i'm actually using it in a django app with tailwindcss v2 as my front end framework but i noticed that forms look kind of odd with alerts :
![image](https://user-images.githubusercontent.com/55496459/107158995-c74dc500-698d-11eb-8961-c0250d7fc62d.png)
i also wanted to ask if the project is still maintained and if it's upgraded to tailwindcss v2.
Thank's in advance

**Comment by smithdc1** [comment]
Hey thanks for this.

Could you share a sample layout that generated this view. This will help me understand what's going on here.

Yes, the project is still maintained. From my testing and reading of the release notes there isn't anything that would mean this package breaks compatibility between v1 and v2. 👍

**Comment by AliMejbar** [comment]
thank's for your feedback , do you plan on doing something for this ? this issue can be closed !

**Comment by smithdc1** [comment]
Ah ok -- I'm afraid I don't have the capacity to look at how this package interacts with others.
