### ISSUE TITLE
Non Field Errors, unclosed div tag

### ISSUE THREAD

**Issue by gigincg** [django-crispy-forms/crispy-tailwind#76]
When non-field errors are rendered, the parent div that starts on line 2 in https://github.com/django-crispy-forms/crispy-tailwind/blob/master/crispy_tailwind/templates/tailwind/errors.html is never closed. This messes up the layout of the page when there are non-field errors

A simple fix would be to add a closing div to the end of the errors.html file.

**Comment by smithdc1** [comment]
Great, thanks for the report. 👍

Are you in a position to open a pr with the fix you suggested? It would really help me out. 

Thanks

**Comment by gigincg** [comment]
I can surely make a PR. It's a simple fix.
