### ISSUE TITLE
Not working for latest release django-crispy-form

### ISSUE THREAD

**Issue by taut-and-yare** [django-crispy-forms/crispy-tailwind#87]
crispy_forms.compatibility.py has been removed in versions of django-crispy-forms >1.11.1, thus giving the following error:

`ImportError raised when trying to load 'crispy_tailwind.templatetags.tailwind_filters': No module named 'crispy_forms.compatibility'`

**Comment by smithdc1** [comment]
Thanks for the report. Fixed in #86
