### ISSUE TITLE
crispy_field load tag

### ISSUE THREAD

**Issue by areski** [django-crispy-forms/crispy-tailwind#95]
I'm seeing this error when using it:

_Compressing... Invalid template /usr/local/lib/python3.9/site-packages/crispy_tailwind/templates/tailwind/layout/inline_field.html:   Invalid block tag on line 9: 'crispy_field', expected 'elif', 'else' or 'endif'. Did you forget to register or load this tag?

Invalid template /usr/local/lib/python3.9/site-packages/crispy_tailwind/templates/tailwind/layout/field_with_buttons.html: Invalid block tag on line 12: 'crispy_field'. Did you forget to register or load this tag?`_

Any pointers on how to fix this?

**Comment by smithdc1** [comment]
Thanks for reporting the issue. 

Looks like `crispy_field` needs to be changed to `tailwind_field` in those templates. Would you be in the market for a PR to fix those? 

We should audit the other templates to makes sure I've not missed anymore.

**Comment by areski** [comment]
I opened a PR, but not sure the fix is right!

**Comment by GitRon** [comment]
PR seems to have been merged ages ago. Closing this ticket.
